<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<CodePage>65001</CodePage>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Models\" />
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.14" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
		<PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.14">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />

		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
		<PackageReference Include="QuestPDF" Version="2026.5.0" />
		<PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\MembersView.axaml.cs">
			<DependentUpon>MembersView.axaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\esseti.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>