// <auto-generated />
using System;
using Esseti.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esseti.Migrations
{
    [DbContext(typeof(EssetiDbContext))]
    [Migration("20260529151429_AddValidationsToModels")]
    partial class AddValidationsToModels
    {
        /// <summary>
        /// Buduje docelowy model bazy danych dla tej migracji.
        /// </summary>
        /// <param name="modelBuilder">Builder modelu Entity Framework.</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Models.Activities.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_id");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_information");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_repeatable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PersonInChargeEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_in_charge_email");

                    b.Property<string>("PersonInChargeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_in_charge_name");

                    b.Property<string>("PersonInChargePhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_in_charge_phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.HasKey("ActivityId")
                        .HasName("p_k_activity");

                    b.ToTable("activity");
                });

            modelBuilder.Entity("Models.Activities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_information");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_end");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_start");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estimated_time");

                    b.Property<string>("Github")
                        .HasColumnType("TEXT")
                        .HasColumnName("github");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("PersonInChargeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_in_charge_id");

                    b.HasKey("ProjectId")
                        .HasName("p_k_project");

                    b.HasIndex("PersonInChargeId");

                    b.ToTable("project");
                });

            modelBuilder.Entity("Models.Activities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("section_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Meetings")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("meetings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.HasKey("SectionId")
                        .HasName("p_k_section");

                    b.ToTable("section");
                });

            modelBuilder.Entity("Models.Activities.SectionMember", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("section_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("SectionId", "MemberId")
                        .HasName("p_k_section_member");

                    b.HasIndex("MemberId");

                    b.ToTable("section_member");
                });

            modelBuilder.Entity("Models.ClubBase.AuthorityRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permissions");

                    b.HasKey("RoleId")
                        .HasName("p_k_authority_role");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("authority_role");
                });

            modelBuilder.Entity("Models.ClubBase.ClubInfo", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("club_id");

                    b.Property<byte[]>("ClubPhoto")
                        .HasColumnType("BLOB")
                        .HasColumnName("club_photo");

                    b.Property<string>("ClubRoom")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("club_room");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("department_id");

                    b.Property<string>("MeetingsSchedule")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("meetings_schedule");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.Property<string>("SupervisorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("supervisor_email");

                    b.Property<string>("SupervisorName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("supervisor_name");

                    b.Property<string>("SupervisorPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("supervisor_phone");

                    b.HasKey("ClubId")
                        .HasName("p_k_club_info");

                    b.HasIndex("DepartmentId");

                    b.ToTable("club_info");
                });

            modelBuilder.Entity("Models.ClubBase.MemberClub", b =>
                {
                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("club_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<string>("ClubRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("club_role");

                    b.HasKey("ClubId", "MemberId")
                        .HasName("p_k_member_club");

                    b.HasIndex("MemberId");

                    b.ToTable("member_club");
                });

            modelBuilder.Entity("Models.Other.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("TripPhoto")
                        .HasColumnType("BLOB")
                        .HasColumnName("trip_photo");

                    b.HasKey("TripId")
                        .HasName("p_k_trip");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("Models.University.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("college_id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<byte[]>("CollegeAvatar")
                        .HasColumnType("BLOB")
                        .HasColumnName("college_avatar");

                    b.Property<string>("NIP")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("NIP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameShort")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_short");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.HasKey("CollegeId")
                        .HasName("p_k_college");

                    b.ToTable("college");
                });

            modelBuilder.Entity("Models.University.CollegeDepartment", b =>
                {
                    b.Property<int>("CollegeDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("college_department_id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<int>("CollegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("college_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.HasKey("CollegeDepartmentId")
                        .HasName("p_k_college_department");

                    b.HasIndex("CollegeId");

                    b.ToTable("college_department");
                });

            modelBuilder.Entity("Models.Users.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("IndexNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("index_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("join_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("major");

                    b.Property<byte[]>("MemberAvatar")
                        .HasColumnType("BLOB")
                        .HasColumnName("member_avatar");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.HasKey("MemberId")
                        .HasName("p_k_member");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Models.Users.UserAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("p_k_user_account");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_account");
                });

            modelBuilder.Entity("account_college", b =>
                {
                    b.Property<int>("account_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("college_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("account_id", "college_id");

                    b.HasIndex("college_id");

                    b.ToTable("account_college");
                });

            modelBuilder.Entity("activity_member", b =>
                {
                    b.Property<int>("activity_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("member_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("activity_id", "member_id");

                    b.HasIndex("member_id");

                    b.ToTable("activity_member");
                });

            modelBuilder.Entity("club_trip", b =>
                {
                    b.Property<int>("club_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("trip_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("club_id", "trip_id");

                    b.HasIndex("trip_id");

                    b.ToTable("club_trip");
                });

            modelBuilder.Entity("project_club", b =>
                {
                    b.Property<int>("club_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("project_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("club_id", "project_id");

                    b.HasIndex("project_id");

                    b.ToTable("project_club");
                });

            modelBuilder.Entity("project_member", b =>
                {
                    b.Property<int>("member_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("project_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("member_id", "project_id");

                    b.HasIndex("project_id");

                    b.ToTable("project_member");
                });

            modelBuilder.Entity("project_sections", b =>
                {
                    b.Property<int>("project_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("section_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("project_id", "section_id");

                    b.HasIndex("section_id");

                    b.ToTable("project_sections");
                });

            modelBuilder.Entity("Models.Activities.Project", b =>
                {
                    b.HasOne("Models.Users.Member", "PersonInCharge")
                        .WithMany()
                        .HasForeignKey("PersonInChargeId")
                        .HasConstraintName("f_k_project__members_person_in_charge_id");

                    b.Navigation("PersonInCharge");
                });

            modelBuilder.Entity("Models.Activities.SectionMember", b =>
                {
                    b.HasOne("Models.Users.Member", "Member")
                        .WithMany("SectionMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_section_member__members_member_id");

                    b.HasOne("Models.Activities.Section", "Section")
                        .WithMany("SectionMembers")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_section_member_section_section_id");

                    b.Navigation("Member");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Models.ClubBase.ClubInfo", b =>
                {
                    b.HasOne("Models.University.CollegeDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("f_k_club_info__college_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Models.ClubBase.MemberClub", b =>
                {
                    b.HasOne("Models.ClubBase.ClubInfo", "Club")
                        .WithMany("MemberClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_member_club_club_info_club_id");

                    b.HasOne("Models.Users.Member", "Member")
                        .WithMany("MemberClubs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_member_club__members_member_id");

                    b.Navigation("Club");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Models.University.CollegeDepartment", b =>
                {
                    b.HasOne("Models.University.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_college_department_college_college_id");

                    b.Navigation("College");
                });

            modelBuilder.Entity("Models.Users.Member", b =>
                {
                    b.HasOne("Models.Users.UserAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("f_k_member__user_accounts_account_id");

                    b.HasOne("Models.ClubBase.AuthorityRole", "AuthorityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("f_k_member_authority_role_role_id");

                    b.Navigation("Account");

                    b.Navigation("AuthorityRole");
                });

            modelBuilder.Entity("account_college", b =>
                {
                    b.HasOne("Models.Users.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.University.College", null)
                        .WithMany()
                        .HasForeignKey("college_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("activity_member", b =>
                {
                    b.HasOne("Models.Activities.Activity", null)
                        .WithMany()
                        .HasForeignKey("activity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Users.Member", null)
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("club_trip", b =>
                {
                    b.HasOne("Models.ClubBase.ClubInfo", null)
                        .WithMany()
                        .HasForeignKey("club_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Other.Trip", null)
                        .WithMany()
                        .HasForeignKey("trip_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project_club", b =>
                {
                    b.HasOne("Models.ClubBase.ClubInfo", null)
                        .WithMany()
                        .HasForeignKey("club_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Activities.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project_member", b =>
                {
                    b.HasOne("Models.Users.Member", null)
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Activities.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project_sections", b =>
                {
                    b.HasOne("Models.Activities.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Activities.Section", null)
                        .WithMany()
                        .HasForeignKey("section_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Activities.Section", b =>
                {
                    b.Navigation("SectionMembers");
                });

            modelBuilder.Entity("Models.ClubBase.ClubInfo", b =>
                {
                    b.Navigation("MemberClubs");
                });

            modelBuilder.Entity("Models.University.College", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Models.Users.Member", b =>
                {
                    b.Navigation("MemberClubs");

                    b.Navigation("SectionMembers");
                });
#pragma warning restore 612, 618
        }
    }
}


